spring:
    profiles:
        active: docker



---
spring:
    autoconfigure:
        exclude:
            - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
    config:
        activate:
            on-profile: local
        import: mail-properties.yml, salt.yml
    data:
        web:
            pageable:
                one-indexed-parameters: true
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: demi
        password: password
        url: jdbc:mysql://localhost:3306/community
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
        open-in-view: off
        properties:
            hibernate:
                format_sql: true
                default_batch_fetch_size: 1000
static:
    profile:
        resource-location: file:///D:/profile/
        save-path: D:\\profile\\
    postImg:
        resource-location: file:///D:/img/
        save-path: D:\\img\\
    upload:
        save-path: D:\\upload\\


server:
    servlet:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
    port: 80

---
spring:
    config:
        activate:
            on-profile: docker
        import: mail-properties.yml, salt.yml
    data:
        web:
            pageable:
                one-indexed-parameters: true
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: demi
        password: password
        url: jdbc:mysql://mysqlDB:3306/community
    jpa:
        open-in-view: off
        properties:
            hibernate:

                default_batch_fetch_size: 1000
        hibernate:
            ddl-auto: none
        generate-ddl: false
    redis:
        host: cache
        port: 6379
static:
    profile:
        save-path: /images/profile/
    postImg:
        save-path: /images/img/
    upload:
        save-path: /upload/


server:
    servlet:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
    port: 80

---
spring:
    autoconfigure:
        exclude:
            - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
    data:
        web:
            pageable:
                one-indexed-parameters: true
    h2:
        console:
            enabled: true
            path: /h2
    config:
        activate:
            on-profile: h2
        import: mail-properties.yml, salt.yml
    datasource:
        driver-class-name: org.h2.Driver
#        url: jdbc:h2:tcp://localhost:9092/~/h2db/testdb
#        username: SA
    jpa:
        hibernate:
            ddl-auto: create

#        show-sql: true
        open-in-view: off
        properties:
            hibernate:
#                format_sql: true
                default_batch_fetch_size: 1000

server:
    port: 80
static:
    profile:
        resource-location: file:///D:/profile/
        save-path: D:\\profile\\
    postImg:
        resource-location: file:///D:/img/
        save-path: D:\\img\\
    upload:
        save-path: D:\\upload\\
