spring:
    servlet:
        multipart:
            max-file-size: 20MB
            max-request-size: 50MB
    profiles:
        active: docker
    data:
        web:
            pageable:
                one-indexed-parameters: true
    config:
        import: salt.yml

server:
    servlet:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
    port: 80



---
spring:
    config:
        activate:
            on-profile: local

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: demi
        password: password
        url: jdbc:mysql://localhost:3306/community
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
        open-in-view: off
        properties:
            hibernate:
                format_sql: true
                default_batch_fetch_size: 1000
static:
    profile:
        resource-location: file:///D:/profile/
        save-path: D:\\profile\\
    postImg:
        resource-location: file:///D:/img/
        save-path: D:\\img\\
    upload:
        save-path: D:\\upload\\


---
spring:
    config:
        activate:
            on-profile: docker
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: demi
        password: password
        url: jdbc:mysql://mysqlDB:3306/community
    jpa:
        open-in-view: off
        properties:
            hibernate:
                default_batch_fetch_size: 1000
        hibernate:
            ddl-auto: none
        generate-ddl: false
static:
    profile:
        save-path: /images/profile/
    postImg:
        save-path: /images/img/
    upload:
        save-path: /upload/
---
spring:
    h2:
        console:
            enabled: true
            path: /h2
    config:
        activate:
            on-profile: h2
    datasource:
        driver-class-name: org.h2.Driver
#        url: jdbc:h2:tcp://localhost:9092/~/h2db/testdb
#        username: SA
    jpa:
        hibernate:
            ddl-auto: create
#        show-sql: true
        open-in-view: off
        properties:
            hibernate:
#                format_sql: true
                default_batch_fetch_size: 1000

static:
    profile:
        resource-location: file:///D:/profile/
        save-path: D:\\profile\\
    postImg:
        resource-location: file:///D:/img/
        save-path: D:\\img\\
    upload:
        save-path: D:\\upload\\
