spring:
    profiles:
        active: local


---
spring:
    config:
        activate:
            on-profile: local
        import: mail-properties.yml, salt.yml
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: demi
        password: password
        url: jdbc:mysql://localhost:3306/community
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
        open-in-view: false
static:
    path:
        resource-location: file:///D:/test/
        save-path: D:\\test\\


server:
    port: 8081

---
spring:
    h2:
        console:
            enabled: true
            path: /h2
    config:
        activate:
            on-profile: h2
        import: mail-properties.yml, salt.yml
    datasource:
        driver-class-name: org.h2.Driver
        username: SA
    jpa:
        hibernate:
            ddl-auto: create

        show-sql: true
        open-in-view: false
server:
    port: 8081
